id: I46FEA9FA
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:27:40.385731
last_modified: 2023-02-08 15:27:40.385824
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  2F8B:
    base_file: 2F8B.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
